# Generated by Django 3.0.7 on 2020-07-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('base_trxid', models.CharField(max_length=50)),
            ],
        ),
    ]
